nodes:
  - address: 172.31.6.78  # EC2 instance Management konsoldan,Rancher makinenin PrivateIP si buraya kopyalanacak
    internal_address: 172.31.6.78 # EC2 instance Management konsoldan,Rancher makinenin PrivateIP si buraya kopyalanacak
    user: ubuntu
    role:
      - controlplane
      - etcd
      - worker

# ignore_docker_version: true

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

ssh_key_path: ~/.ssh/petclinic-rancher.pem

# Required for external TLS termination with
# ingress-nginx v0.22+
ingress:
  provider: nginx
  options:
    use-forwarded-headers: "true"